from pathlib import Path
import re


def replace(path, old, new, count=1):
    p=Path(path); text=p.read_text()
    if old not in text: raise SystemExit(f"missing marker in {path}: {old[:120]!r}")
    p.write_text(text.replace(old,new,count))

# Preference ownership: persist sort alongside view, per library scope.
replace("src/assets/js/domain/preferences.js",'export const VIEW_PREFIX = "sg-view:";\nexport const MOBILE_FILTER_PREFIX = "sg-mobile-filters-collapsed:";', 'export const VIEW_PREFIX = "sg-view:";\nexport const SORT_PREFIX = "sg-sort:";\nexport const MOBILE_FILTER_PREFIX = "sg-mobile-filters-collapsed:";')
replace("src/assets/js/domain/preferences.js",'export function mobileFilterKey(scope = "main") {\n  return `${MOBILE_FILTER_PREFIX}${cleanScope(scope)}`;\n}', 'export function sortKey(scope = "main") {\n  return `${SORT_PREFIX}${cleanScope(scope)}`;\n}\n\nexport function mobileFilterKey(scope = "main") {\n  return `${MOBILE_FILTER_PREFIX}${cleanScope(scope)}`;\n}')
replace("src/assets/js/domain/preferences.js",'export function setLibraryView(scope = "main", view = "grid") {\n  return writeText(viewKey(scope), view === "compact" ? "compact" : "grid");\n}', 'export function setLibraryView(scope = "main", view = "grid") {\n  return writeText(viewKey(scope), view === "compact" ? "compact" : "grid");\n}\n\nexport function librarySort(scope = "main") {\n  const value = readText(sortKey(scope), "recent");\n  return ["recent", "title", "author", "year", "volumes"].includes(value) ? value : "recent";\n}\n\nexport function setLibrarySort(scope = "main", sort = "recent") {\n  const value = ["recent", "title", "author", "year", "volumes"].includes(sort) ? sort : "recent";\n  return writeText(sortKey(scope), value);\n}')
replace("src/assets/js/domain/preferences.js",'return value === PINNED_KEY || value === PINNED_NAV_COLLAPSED_KEY || value === ADULT_ACK_KEY || value.startsWith(VIEW_PREFIX) || value.startsWith(MOBILE_FILTER_PREFIX);', 'return value === PINNED_KEY || value === PINNED_NAV_COLLAPSED_KEY || value === ADULT_ACK_KEY || value.startsWith(VIEW_PREFIX) || value.startsWith(SORT_PREFIX) || value.startsWith(MOBILE_FILTER_PREFIX);')

# Context-aware facet counts. Counts preserve all other active filters.
model=Path("src/assets/js/library-model.js"); text=model.read_text()
append='''\n\nfunction cloneState(state) {\n  return { ...state, tags: new Set(state?.tags || []) };\n}\n\nexport function contextualFilterOptions(items, state, dependencies = {}) {\n  const base = filterOptions(items);\n  const count = patch => filterAndSort(items, Object.assign(cloneState(state), patch), dependencies).length;\n  const authorCounts = new Map(base.authors.map(value => [value, count({ author: value })]));\n  const translatorCounts = new Map(base.translators.map(value => [value, count({ translator: value })]));\n  const genreCounts = new Map(base.genres.map(value => [value, count({ genre: value })]));\n  const yearCounts = new Map(base.years.map(value => [value, count({ year: value })]));\n  const volumeCounts = new Map(VALID_VOLUME_RANGES.size ? [...VALID_VOLUME_RANGES].filter(Boolean).map(value => [value, count({ volumeRange: value })]) : []);\n  const tagCounts = new Map(base.tags.map(value => { const tags = new Set(state?.tags || []); tags.add(value); return [value, count({ tags })]; }));\n  return { ...base, authorCounts, translatorCounts, genreCounts, yearCounts, volumeCounts, tagCounts };\n}\n'''
if 'export function contextualFilterOptions' not in text: model.write_text(text+append)

# Random suggestion gets an explicit reroll affordance only in random suggestion mode.
replace("src/assets/js/library-renderers.js",'panel.innerHTML = `<div class="continue-mark${cover ? " continue-cover" : ""}">${cover ? `<img src="${esc(cover)}" alt="" loading="eager" decoding="async">` : "✦"}</div><div><strong>${esc(title)}</strong><span>${esc(context)}</span></div><a ${attrs(action, esc)} href="${action.href}">${esc(action.label)}</a>`;', 'const reroll = mode === "suggestion" && current.suggestion === "random" ? `<button class="another-suggestion" type="button" data-another-suggestion aria-label="Show another reading suggestion">Another suggestion ↻</button>` : "";\n  panel.innerHTML = `<div class="continue-mark${cover ? " continue-cover" : ""}">${cover ? `<img src="${esc(cover)}" alt="" loading="eager" decoding="async">` : "✦"}</div><div><strong>${esc(title)}</strong><span>${esc(context)}</span></div><div class="continue-actions"><a ${attrs(action, esc)} href="${action.href}">${esc(action.label)}</a>${reroll}</div>`;')

# Library controller.
p=Path("src/assets/js/library.js"); text=p.read_text()
text=text.replace('const suggestionRandom=Math.random();','let suggestionRandom=Math.random();')
text=text.replace('const options=model.filterOptions(state.items);','const options=model.contextualFilterOptions(state.items,state,{pinnedIds:domain.preferences.pinnedIds(),seriesFinished:readingStatus.seriesFinished});')
text=text.replace("options.authors.map(author=>`<option value=\"${esc(author)}\">${esc(author)}</option>`).join(\"\")", "options.authors.map(author=>{const count=options.authorCounts.get(author)||0;return `<option value=\"${esc(author)}\" ${!count&&state.author!==author?\"disabled\":\"\"}>${esc(author)} (${count})</option>`}).join(\"\")")
text=text.replace("options.translators.map(translator=>`<option value=\"${esc(translator)}\">${esc(translator)}</option>`).join(\"\")", "options.translators.map(translator=>{const count=options.translatorCounts.get(translator)||0;return `<option value=\"${esc(translator)}\" ${!count&&state.translator!==translator?\"disabled\":\"\"}>${esc(translator)} (${count})</option>`}).join(\"\")")
text=text.replace("options.genres.map(genre=>`<option value=\"${esc(genre)}\">${esc(genre)}</option>`).join(\"\")", "options.genres.map(genre=>{const count=options.genreCounts.get(genre)||0;return `<option value=\"${esc(genre)}\" ${!count&&state.genre!==genre?\"disabled\":\"\"}>${esc(genre)} (${count})</option>`}).join(\"\")")
text=text.replace("options.years.map(year=>`<option value=\"${esc(year)}\">${esc(year)}</option>`).join(\"\")", "options.years.map(year=>{const count=options.yearCounts.get(year)||0;return `<option value=\"${esc(year)}\" ${!count&&state.year!==year?\"disabled\":\"\"}>${esc(year)} (${count})</option>`}).join(\"\")")
text=text.replace("options.tags.map(tag=>`<option value=\"${esc(tag)}\">${esc(tag)}</option>`).join(\"\")", "options.tags.map(tag=>{const count=options.tagCounts.get(tag)||0;return `<option value=\"${esc(tag)}\" ${!count&&!state.tags.has(tag)?\"disabled\":\"\"}>${esc(tag)} (${count})</option>`}).join(\"\")")
# Rebuild static volume options with contextual counts after the existing assignment block.
text=text.replace('$("#tagSelect").innerHTML=', 'if($("#volumeCountSelect")){const labels={"1":"Single volume","2-5":"2–5 volumes","6-10":"6–10 volumes","11+":"11+ volumes"};$("#volumeCountSelect").innerHTML=`<option value="">Any size</option>`+[...model.VALID_VOLUME_RANGES].filter(Boolean).map(value=>{const count=options.volumeCounts.get(value)||0;return `<option value="${value}" ${!count&&state.volumeRange!==value?"disabled":""}>${labels[value]} (${count})</option>`}).join("")}\n    $("#tagSelect").innerHTML=',1)
# URL preference fallbacks.
text=text.replace('state.sort=model.VALID_SORTS.has(params.get("sort"))?params.get("sort"):"recent";', 'state.sort=model.VALID_SORTS.has(params.get("sort"))?params.get("sort"):domain.preferences.librarySort(scope);')
text=text.replace('if(view==="grid"||view==="compact")state.view=view;', 'if(view==="grid"||view==="compact")state.view=view;else state.view=domain.preferences.libraryView(scope);')
# Active filter count / Clear all.
marker='''  function renderActiveFilters(){\n    const container=$("#activeTags");'''
replacement='''  function activeFilterCount(){\n    return Number(Boolean(state.query.trim()))+Number(Boolean(state.author))+Number(Boolean(state.translator))+Number(Boolean(state.genre))+Number(Boolean(state.year))+Number(Boolean(state.volumeRange))+Number(Boolean(state.readingStatus))+Number(Boolean(state.pinnedOnly))+state.tags.size;\n  }\n\n  function renderActiveFilters(){\n    const container=$("#activeTags");'''
if marker not in text: raise SystemExit('renderActiveFilters marker missing')
text=text.replace(marker,replacement,1)
text=text.replace('    [...state.tags].sort((a,b)=>a.localeCompare(b)).forEach(tag=>pills.push(tagPill(tag)));\n    container.innerHTML=pills.join("");', '    [...state.tags].sort((a,b)=>a.localeCompare(b)).forEach(tag=>pills.push(tagPill(tag)));\n    if(activeFilterCount()>=2)pills.push(`<button type="button" class="active-filter-clear-all" data-clear-all-filters title="Clear all result filters"><span class="active-filter-pill-label">Clear all</span><span aria-hidden="true">↺</span></button>`);\n    container.innerHTML=pills.join("");')
# Empty-state actionable constraints.
text=text.replace('''  function apply({historyMode=null,preserveCount=false}={}){''','''  function renderEmptyActions(){\n    const root=$("#emptyActions");if(!root)return;\n    if(state.filtered.length||!activeFilterCount()){root.replaceChildren();return}\n    const actions=[];\n    const add=(label,key)=>actions.push(`<button type="button" data-clear-filter="${esc(key)}">${esc(label)} ×</button>`);\n    if(state.query.trim())add(`Search: ${state.query.trim()}`,"query");if(state.author)add(`Author: ${state.author}`,"author");if(state.translator)add(`Translator: ${state.translator}`,"translator");if(state.genre)add(`Genre: ${state.genre}`,"genre");if(state.year)add(`Year: ${state.year}`,"year");if(state.volumeRange)add("Volume count","volumeRange");if(state.readingStatus)add("Reading state","readingStatus");if(state.pinnedOnly)add("Pinned only","pinnedOnly");[...state.tags].forEach(tag=>actions.push(`<button type="button" data-remove-tag="${esc(tag)}">${esc(tag)} ×</button>`));\n    actions.push('<button type="button" class="empty-reset" data-clear-all-filters>Reset all filters</button>');root.innerHTML=actions.join("");\n  }\n\n  function apply({historyMode=null,preserveCount=false}={}){''')
text=text.replace('''    state.filtered=model.filterAndSort(state.items,state,{pinnedIds:domain.preferences.pinnedIds(),seriesFinished:readingStatus.seriesFinished});\n    state.renderedCount=0;''','''    state.filtered=model.filterAndSort(state.items,state,{pinnedIds:domain.preferences.pinnedIds(),seriesFinished:readingStatus.seriesFinished});\n    state.renderedCount=0;collectFilters();''')
text=text.replace('''    syncControls();\n    const target=''', '''    syncControls();renderEmptyActions();\n    const target=''')
text=text.replace('''    const grid=$("#catalogGrid");\n    if(grid){grid.innerHTML="";grid.classList.toggle("compact",state.view==="compact")}''', '''    const grid=$("#catalogGrid");\n    if(grid){grid.classList.add("is-updating");grid.innerHTML="";grid.classList.toggle("compact",state.view==="compact");requestAnimationFrame(()=>grid.classList.remove("is-updating"))}''')
# Preference writes.
text=re.sub(r'(\$\("#sortSelect"\)\?\.addEventListener\("change",event=>\{state\.sort=event\.target\.value;)(apply\(\{historyMode:"push"\}\)\}\);)', r'\1domain.preferences.setLibrarySort(scope,state.sort);\2', text)
text=re.sub(r'(button\.addEventListener\("click",\(\)=>\{state\.view=button\.dataset\.view;)([^}]*apply\(\{historyMode:"push"[^}]*\}\))', r'\1domain.preferences.setLibraryView(scope,state.view);\2', text)
# Event delegation: insert universal clear/reroll handler before bindControls end listener setup.
needle='''  function bindControls(){\n'''
insert='''  function handleFilterAction(event){\n    const clearAll=event.target.closest("[data-clear-all-filters]");if(clearAll){clearFilters({historyMode:"push"});return true}\n    const remove=event.target.closest("[data-remove-tag]");if(remove){state.tags.delete(remove.dataset.removeTag);apply({historyMode:"push"});return true}\n    const clear=event.target.closest("[data-clear-filter]");if(clear&&clearNamedFilter(clear.dataset.clearFilter)){apply({historyMode:"push"});return true}\n    const reroll=event.target.closest("[data-another-suggestion]");if(reroll){suggestionRandom=Math.random();renderContinue();return true}\n    return false;\n  }\n\n  function bindControls(){\n    $("#activeTags")?.addEventListener("click",handleFilterAction);$("#emptyActions")?.addEventListener("click",handleFilterAction);$("#continuePanel")?.addEventListener("click",handleFilterAction);\n'''
if needle not in text: raise SystemExit('bindControls marker missing')
text=text.replace(needle,insert,1)
p.write_text(text)

# Empty actions in both Library entrypoints.
for path in ["src/index.html","src/nsfw.html"]:
    p=Path(path); text=p.read_text()
    old='<div id="emptyState" class="empty-state hidden" role="status"><span aria-hidden="true">✦</span><h2>The Garden is quiet.</h2><p id="emptyMessage">No shelf answers the current path.</p></div>'
    if old not in text: raise SystemExit(f'empty state marker missing {path}')
    p.write_text(text.replace(old,'<div id="emptyState" class="empty-state hidden" role="status"><span aria-hidden="true">✦</span><h2>The Garden is quiet.</h2><p id="emptyMessage">No shelf answers the current path.</p><div id="emptyActions" class="empty-filter-actions"></div></div>'))

# CSS polish.
p=Path("src/assets/css/library-features.css"); text=p.read_text()
text += '''\n\n/* v2.4 interaction polish — discovery feedback, filter actions, and suggestion agency. */\n.active-filter-tags .active-filter-clear-all{border-style:dashed;color:var(--muted);background:transparent}.active-filter-tags .active-filter-clear-all:hover{color:var(--leaf2)}\n.empty-filter-actions{margin-top:14px;display:flex;flex-wrap:wrap;justify-content:center;gap:7px}.empty-filter-actions:empty{display:none}.empty-filter-actions button{padding:7px 10px;border:1px solid var(--line);border-radius:999px;color:var(--muted);background:rgba(255,255,255,.025);cursor:pointer}.empty-filter-actions button:hover,.empty-filter-actions button:focus-visible{color:var(--leaf2);border-color:var(--line2);outline:none}.empty-filter-actions .empty-reset{border-style:dashed}\n.catalog-grid{transition:opacity .16s ease,transform .16s ease}.catalog-grid.is-updating{opacity:.45;transform:translateY(3px)}\n.continue-actions{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.continue-actions>a{white-space:nowrap}.another-suggestion{padding:7px 9px;border:0;color:var(--dim);background:transparent;cursor:pointer;font-size:.66rem}.another-suggestion:hover,.another-suggestion:focus-visible{color:var(--leaf2);outline:none}\n.adult-library .active-filter-tags .active-filter-clear-all,.adult-library .empty-filter-actions button{color:#9b7984}.adult-library .empty-filter-actions button:hover,.adult-library .empty-filter-actions button:focus-visible,.adult-library .another-suggestion:hover,.adult-library .another-suggestion:focus-visible{color:var(--adult-accent-strong);border-color:var(--adult-border-strong)}\n@media(prefers-reduced-motion:reduce){.catalog-grid{transition:none}.catalog-grid.is-updating{transform:none}}\n'''
p.write_text(text)
